<a href="https://colab.research.google.com/github/odevhesabi/Odevler/blob/main/A_02_BasicsOfNumPyArray_tr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**(1)** Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [ ]:
import numpy as np
squaremeter=[1,2,3,4,5,6,7,8,9,10]
rooms=[1,2,3,4,5,6,7,8,9,10]
price=[3,3,3,3,3,3,3,3,3,3]

newarray=np.array([squaremeter, rooms, price])
print(newarray)

**(2)** Transpose the array you have created, so that every line can represent features of one house.

In [5]:
newarray = newarray.transpose()
print(newarray)

[[ 1  1  3]
 [ 2  2  3]
 [ 3  3  3]
 [ 4  4  3]
 [ 5  5  3]
 [ 6  6  3]
 [ 7  7  3]
 [ 8  8  3]
 [ 9  9  3]
 [10 10  3]]


**(3)** Display the shape of the array and explain what it means.

In [6]:
print(newarray.shape)

10 Satır, 3 sütun.

(10, 3)


**(4)** Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [ ]:
def array1(row, column):
  newarray=np.array